// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUser struct {
	Name     string `json:"name"`
	Lastname string `json:"lastname"`
	Age      string `json:"age"`
}

type Query struct {
}

type UpdateUser struct {
	Name     *string `json:"name,omitempty"`
	Lastname *string `json:"lastname,omitempty"`
	Age      *string `json:"age,omitempty"`
}
